### ISSUE TITLE
Write project README

### ISSUE THREAD

**Issue by matshou** [yooksi/daylight#2]
This should at the very least contain a detailed description of what the mod is about.

Reference material: [A Beginners Guide to writing a Kickass README](https://gist.github.com/akashnimare/7b065c12d9750578de8e705fb4771d2f).

**Comment by zixi-nox** [comment]
##### Are you tired of guessing what time of the day it is? You don't have resources to make a clock or it's not precise enough for you? Were you ever killed by mobs seconds away from your make-shift house and dropped all the mined goods because your time estimation was slightly off?  Well, your dog days are over. Team YoCo proudly presents you our mod Daylight.  Located in the upper right corner of your screen ,Daylight  is a precise indicator of the current time in the game. With graceful animation that displays solar and lunar changes you will always know when to come out of your man cave.

##### Daylight will make your playing experience much better knowing you don't have to think about time. It's size and frame is delicate so you will not even notice it's presence. Just joking...you will cause it's awesome! In matter of fact, it's better then wolfs...I mean clocks! All you have to do is visit Curse Forge, download and install it and of course, have fun! 

Team Yoco

**Comment by amazingcoco** [comment]
Are you tired of guessing what time of the day it is? You don't have resources to make a clock or it's not precise enough for you? Were you ever killed by mobs seconds away from your make-shift house and dropped all the mined goods because your time estimation was slightly off?  Well, your dog days are over. 

Team Yoco proudly presents you our mod Daylight.  Located in the upper right corner of your screen (configurable) ,Daylight  is a precise indicator of the current time in the game. With graceful animation that displays solar and lunar changes you will always know when to come out of your man cave.

 Daylight will make your playing experience much better knowing you don't have to think about time. It's size and frame is delicate so you will not even notice it's presence. Just joking...you will cause it's awesome! In matter of fact, it's better then wolfs...I mean clocks! All you have to do is visit Curse Forge, download and install it and of course, have fun!  

Team Yoco

**Comment by matshou** [comment]
I like that, could you make a commit that creates a README with that content?

**Comment by amazingcoco** [comment]
@yooksi Do you think some changes in text should be made? Are you satisfied with the description?

**Comment by matshou** [comment]
Perhaps some rephrasing is needed, but we can handle that through version control :package:

**Comment by amazingcoco** [comment]
Yes, I agree! The concept is alright, but still the text is rough around the edges.

**Comment by matshou** [comment]
@amazingcoco We need some screenshots for project docs, you think you can take a few and post them here? If you feel up for it go grab the mod from the [releases](https://github.com/yooksi/daylight/releases) section and install it as any other mod. You also need the latest version of [CocoLib](https://github.com/yooksi/cocolib/releases/tag/1.15.2-0.2.0) also obtainable from Github.

**Comment by amazingcoco** [comment]
Thanks a lot, I'm on it!
